'use client';

import { useEffect, useMemo, useRef, useState } from 'react';
import * as Blockly from 'blockly';
import { javascriptGenerator } from 'blockly/javascript';

const API = process.env.NEXT_PUBLIC_DERIV_API_BASE || 'https://api.derivws.com';
const CLIENT_ID = process.env.NEXT_PUBLIC_DERIV_CLIENT_ID || '';
const REDIRECT_URI = process.env.NEXT_PUBLIC_DERIV_REDIRECT_URI || '';
const LEGACY_APP_ID = process.env.NEXT_PUBLIC_DERIV_LEGACY_APP_ID || '';

type Account = { account_id:string; balance:number; currency:string; account_type:'demo'|'real'; status:string };
type Tick = { epoch:number; quote:number };

function base64Url(bytes: Uint8Array){let s='';for(const b of bytes)s+=String.fromCharCode(b);return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');}
async function pkce(){const raw=new Uint8Array(64);crypto.getRandomValues(raw);const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~';let verifier='';for(const b of raw)verifier+=chars[b%chars.length];const hash=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier));return {verifier,challenge:base64Url(new Uint8Array(hash))};}

export default function Home(){
 const blocklyRef=useRef<HTMLDivElement>(null); const chartRef=useRef<HTMLCanvasElement>(null);
 const wsRef=useRef<WebSocket|null>(null); const [ticks,setTicks]=useState<Tick[]>([]); const [symbol,setSymbol]=useState('R_100');
 const [token,setToken]=useState(''); const [accounts,setAccounts]=useState<Account[]>([]); const [account,setAccount]=useState<Account|null>(null);
 const [connected,setConnected]=useState(false); const [running,setRunning]=useState(false); const [stake,setStake]=useState('1'); const [duration,setDuration]=useState('1'); const [unit,setUnit]=useState('t'); const [contract,setContract]=useState('CALL');
 const [logs,setLogs]=useState<string[]>(['Workspace ready. Connect a Deriv account to enable trading.']); const [journal,setJournal]=useState('');
 const toolbox=useMemo(()=>({kind:'categoryToolbox',contents:[
  {kind:'category',name:'Trade',colour:'#1677d2',contents:[{kind:'block',type:'controls_if'},{kind:'block',type:'math_number'},{kind:'block',type:'logic_compare'}]},
  {kind:'category',name:'Analysis',colour:'#20a67a',contents:[{kind:'block',type:'variables_get'},{kind:'block',type:'math_arithmetic'}]},
  {kind:'category',name:'Conditions',colour:'#e0a43c',contents:[{kind:'block',type:'logic_boolean'},{kind:'block',type:'logic_operation'}]},
  {kind:'category',name:'Utility',colour:'#9b6ad6',contents:[{kind:'block',type:'text'},{kind:'block',type:'text_print'}]}
 ]}),[]);

 useEffect(()=>{const saved=sessionStorage.getItem('deriv_token');if(saved)setToken(saved)},[]);
 useEffect(()=>{if(!blocklyRef.current)return; const ws=Blockly.inject(blocklyRef.current,{toolbox,grid:{spacing:20,length:3,colour:'#20344b',snap:true},zoom:{controls:true,wheel:true,startScale:.9,maxScale:1.5,minScale:.55},trashcan:true}); const root=ws.newBlock('controls_if');root.initSvg();root.render();root.moveBy(40,40); return()=>ws.dispose();},[toolbox]);
 useEffect(()=>{const draw=()=>{const c=chartRef.current;if(!c)return;const d=devicePixelRatio||1,r=c.getBoundingClientRect();c.width=r.width*d;c.height=r.height*d;const x=c.getContext('2d');if(!x)return;x.scale(d,d);x.clearRect(0,0,r.width,r.height);x.strokeStyle='#17304b';x.lineWidth=1;for(let i=1;i<6;i++){const y=i*r.height/6;x.beginPath();x.moveTo(0,y);x.lineTo(r.width,y);x.stroke()}if(ticks.length<2)return;const vals=ticks.map(t=>t.quote),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;x.strokeStyle='#38a0ff';x.lineWidth=2;x.beginPath();vals.forEach((v,i)=>{const px=i*(r.width/(vals.length-1));const py=r.height-22-((v-min)/span)*(r.height-42);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();};draw();window.addEventListener('resize',draw);return()=>window.removeEventListener('resize',draw)},[ticks]);
 useEffect(()=>{if(!token)return;sessionStorage.setItem('deriv_token',token);fetch(`${API}/trading/v1/options/accounts`,{headers:{'Deriv-App-ID':CLIENT_ID,Authorization:`Bearer ${token}`}}).then(r=>r.json()).then(j=>{const list=Array.isArray(j.data)?j.data:[];setAccounts(list);setAccount(list.find((a:Account)=>a.account_type==='demo')||list[0]||null);log(`Loaded ${list.length} Deriv account(s).`)}).catch(e=>log(`Account error: ${e.message}`));},[token]);
 useEffect(()=>{const ws=new WebSocket('wss://api.derivws.com/trading/v1/options/ws/public');wsRef.current=ws;ws.onopen=()=>{ws.send(JSON.stringify({ticks:symbol,subscribe:1,req_id:10}));setConnected(true)};ws.onmessage=e=>{const j=JSON.parse(e.data);if(j.tick){setTicks(v=>[...v.slice(-119),{epoch:j.tick.epoch,quote:Number(j.tick.quote)}])}};ws.onclose=()=>setConnected(false);return()=>ws.close()},[symbol]);
 function log(s:string){setLogs(v=>[`${new Date().toLocaleTimeString()}  ${s}`,...v].slice(0,100))}
 async function login(){if(!CLIENT_ID||!REDIRECT_URI){alert('Set NEXT_PUBLIC_DERIV_CLIENT_ID and NEXT_PUBLIC_DERIV_REDIRECT_URI in Vercel first.');return}const {verifier,challenge}=await pkce();const state=crypto.randomUUID();sessionStorage.setItem('pkce_verifier',verifier);sessionStorage.setItem('oauth_state',state);const q=new URLSearchParams({response_type:'code',client_id:CLIENT_ID,redirect_uri:REDIRECT_URI,scope:'trade',state,code_challenge:challenge,code_challenge_method:'S256'});if(LEGACY_APP_ID)q.set('app_id',LEGACY_APP_ID);location.href=`https://auth.deriv.com/oauth2/auth?${q}`}
 function logout(){setToken('');setAccounts([]);setAccount(null);sessionStorage.removeItem('deriv_token');log('Disconnected.')}
 async function trade(){if(!account||!token){log('Connect a Deriv account first.');return}setRunning(true);try{const otpRes=await fetch(`${API}/trading/v1/options/accounts/${account.account_id}/otp`,{method:'POST',headers:{'Deriv-App-ID':CLIENT_ID,Authorization:`Bearer ${token}`}});const otp=await otpRes.json();if(!otpRes.ok)throw new Error(JSON.stringify(otp));const ws=new WebSocket(otp.data.url);ws.onopen=()=>{ws.send(JSON.stringify({proposal:1,amount:Number(stake),basis:'stake',contract_type:contract,currency:account.currency,duration:Number(duration),duration_unit:unit,underlying_symbol:symbol,subscribe:1,req_id:21}))};ws.onmessage=e=>{const j=JSON.parse(e.data);if(j.proposal){log(`Proposal received: ${j.proposal.id}`);ws.send(JSON.stringify({buy:j.proposal.id,price:Number(stake),req_id:22}))}else if(j.buy){log(`Contract purchased: ${j.buy.contract_id}`);setJournal(`BUY ${j.buy.contract_id} • ${symbol} • ${contract}`)}else if(j.error){log(`Trade error: ${j.error.message}`);ws.close();setRunning(false)}};ws.onerror=()=>{log('Trading WebSocket error.');setRunning(false)};ws.onclose=()=>setRunning(false)}catch(e:any){log(`Trade failed: ${e.message}`);setRunning(false)}}
 function generate(){const ws=Blockly.getMainWorkspace();if(!ws)return;try{setJournal(javascriptGenerator.workspaceToCode(ws)||'No executable blocks yet.');log('Generated strategy code from Blockly workspace.')}catch(e:any){log(`Generator error: ${e.message}`)}}
 return <div className="app">
  <header className="topbar"><div className="brand">Real <span>Deriv Bot</span></div><div className="status">{connected?'● Market stream live':'○ Market stream offline'}</div><div className="grow"/><div className="status">{account?`${account.account_type.toUpperCase()} • ${account.currency} ${Number(account.balance).toFixed(2)}`:'Not connected'}</div>{token?<button className="btn" onClick={logout}>Disconnect</button>:<button className="btn primary" onClick={login}>Login with Deriv</button>}</header>
  <main className="workspace">
   <aside className="panel sidebar"><div className="panel-head">Blocks <span>⌘</span></div><div className="side-scroll"><div className="section-title">Trade parameters</div><div className="block-item"><i className="dot"/> Trade parameters</div><div className="block-item"><i className="dot green"/> Purchase conditions</div><div className="block-item"><i className="dot yellow"/> Restart trading conditions</div><div className="block-item"><i className="dot red"/> Sell conditions</div><div className="section-title">Analysis</div><div className="block-item"><i className="dot green"/> Tick analysis</div><div className="block-item"><i className="dot green"/> Candle analysis</div><div className="block-item"><i className="dot green"/> Technical indicators</div><div className="section-title">Quick strategy</div><button className="btn small" onClick={()=>log('Quick Strategy: Martingale template selected.')}>Martingale</button> <button className="btn small" onClick={()=>log('Quick Strategy: D’Alembert template selected.')}>D’Alembert</button> <button className="btn small" onClick={()=>log('Quick Strategy: Oscar’s Grind template selected.')}>Oscar’s Grind</button></div></aside>
   <section className="panel builder"><div className="panel-head">Bot Builder <span>Drag blocks to build your strategy</span></div><div className="builder-tools"><button className="btn small" onClick={generate}>Generate</button><button className="btn small" onClick={()=>log('Strategy save/import UI is ready for XML integration.')}>Save</button><button className="btn small" onClick={()=>log('Import XML selected.')}>Import</button><div className="grow"/><button className={`btn small ${running?'danger':'primary'}`} onClick={trade}>{running?'Trading…':'Run bot'}</button></div><div ref={blocklyRef} className="blockly-wrap"/></section>
   <aside className="panel trade-panel"><div className="panel-head">Charts & Trading <span>{symbol}</span></div><div className="chart-wrap"><canvas ref={chartRef} className="chart-canvas"/><div className="chart-label">{symbol} • live ticks</div></div><div className="controls"><div className="field"><label>Asset</label><select value={symbol} onChange={e=>setSymbol(e.target.value)}><option>R_100</option><option>R_75</option><option>R_50</option><option>1HZ100V</option><option>1HZ75V</option><option>frxEURUSD</option></select></div><div className="field"><label>Contract</label><select value={contract} onChange={e=>setContract(e.target.value)}><option value="CALL">Rise / Call</option><option value="PUT">Fall / Put</option><option value="MULTUP">Multiplier Up</option><option value="MULTDOWN">Multiplier Down</option></select></div><div className="field"><label>Stake</label><input value={stake} onChange={e=>setStake(e.target.value)} inputMode="decimal"/></div><div className="field"><label>Duration</label><input value={duration} onChange={e=>setDuration(e.target.value)} inputMode="numeric"/></div><div className="field"><label>Unit</label><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="t">Ticks</option><option value="s">Seconds</option><option value="m">Minutes</option></select></div><div className="field"><label>Account</label><select value={account?.account_id||''} onChange={e=>setAccount(accounts.find(a=>a.account_id===e.target.value)||null)}><option value="">Connect account</option>{accounts.map(a=><option key={a.account_id} value={a.account_id}>{a.account_type} • {a.account_id}</option>)}</select></div></div><div className="trade-actions"><button className="btn primary" onClick={trade}>Purchase</button><button className="btn danger" onClick={()=>{setRunning(false);log('Bot paused.')}}>Pause</button></div><div className="tabs"><div className="tab active">Transactions</div><div className="tab">Journal</div></div><div className="log">{journal&&<div className="log-line">{journal}</div>}{logs.map((x,i)=><div className="log-line" key={i}>{x}</div>)}</div></aside>
  </main><footer className="bottom"><span>Real workspace</span><span>Blockly strategy engine</span><span>Deriv WebSocket market stream</span><span>API: {API.replace('https://','')}</span></footer>
 </div>
}
